### ISSUE TITLE
mimic-iv-2.0/antibiotic.csv file

### ISSUE THREAD

**Issue by martijnsiepel01** [WilliamBolton/iv_to_oral#1]
Hi,

I want to replicate your results, but I'm unsure on how/where you got "mimic-iv-2.0/antibiotic.csv". Did you make that yourself? I made a script to filter the MIMIC IV prescriptions file by converting NDC codes to ATC codes, and selecting all prescription codes with ATC = J01%. However, my columns are different than yours are. Could you share this file with me perhaps? Or the creation script?

**Comment by WilliamBolton** [comment]
Hi Martijn, thanks for your comment! The MIMIC IV antibiotic.csv file can be found inside the mimic_derived folder. To access this I opened the data in Google bigquery and followed physionet-data -> mimic_derived -> antibiotic. From there you should be able to download the file. Unfortunately I am unable to share the file as this would be against MIMIC's terms of use. Let me know if you have any other questions.
